#ifndef __INSTRUMENTS_H__
#define __INSTRUMENTS_H__

#define INSTRUMENT_BASS 0
#define INSTRUMENT_SINE 1
#define INSTRUMENT_PULSE01 2
#define INSTRUMENT_PULSE01 3
#define INSTRUMENT_HOLI 4
#define INSTRUMENT_KICK 5
#define INSTRUMENT_SNAREDRUM 6
#define INSTRUMENT_HAT 7
#define INSTRUMENT_PIII 8
#define INSTRUMENT_HIDDEN 9
#define INSTRUMENT_PIII 10
#define INSTRUMENT_BIIIIIII 12

#endif

